version: "1.0"
info:
  model: int-scaffold
packages:
- name: GitProjectTestProject
  gitServerName: https://github.com/
  gitUrl: https://github.com/y509522/GitProjectTestProject
  gitUsername: y509522
  gitBranch: main
